mainSections = ["post"]
# featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[footer]
since = 2020

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "üç•"
subtitle = "A blog about tech and stuff"

[sidebar.avatar]
enabled = true
local = true
src = "img/favicon.png"

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[imageProcessing]

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
